# Variables de servicio
keycloak-url: http://localhost:9090
server-port: 8080
keycloak-secret: BeYS8ySrXHAzGjCq8iZz0apg99KkZJYx
kafka-broker: localhost:9092

# Descripción del servicio
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    stream:
      kafka:
        binder:
          brokers: ${kafka-broker}
      bindings:
        sendMessage-out-0:
          destination: user-management
  kafka:
    bootstrap-servers: ${kafka-broker}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-url}/realms/landmates/protocol/openid-connect/certs

server:
  port: ${server-port:8080}

keycloak:
  token-url: ${keycloak-url}/realms/landmates/protocol/openid-connect/token
  client-id: landmates-gateway
  client-secret: ${keycloak-secret:BeYS8ySrXHAzGjCq8iZz0apg99KkZJYx}

info:
  app:
    name: Landmates Gateway Service
    description: API Gateway for routing and filtering
    version: 0.0.1
