# Variables de servicio
keycloak-url: http://keycloak-server:9090
server-port: 8080
keycloak-secret: BeYS8ySrXHAzGjCq8iZz0apg99KkZJYx
kafka-broker: 54.224.168.24:9092

# Descripción del servicio
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    stream:
      kafka:
        binder:
          brokers: ${kafka-broker}
      bindings:
        sendMessage-out-0:
          destination: user-management
  kafka:
    bootstrap-servers: ${kafka-broker}

server:
  port: ${server-port:8080}

keycloak:
  token-url: ${keycloak-url}/realms/landmates/protocol/openid-connect/token
  client-id: landmates-gateway
  client-secret: ${keycloak-secret:BeYS8ySrXHAzGjCq8iZz0apg99KkZJYx}

info:
  app:
    name: Landmates Gateway Service
    description: API Gateway for routing and filtering
    version: 0.0.1

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
    - name: Users Service
      url: /aggregate/users/v3/api-docs
    - name: Marketplace
      url: /aggregate/marketplace/v3/api-docs
    - name: Gateway Auth
      url: /api-docs
