spring:
  data:
    mongodb:
      uri: mongodb+srv://ms-client:LandMates2024@clusterms.xphsc.mongodb.net/?retryWrites=true&w=majority&appName=ClusterMS
      database: marketplace
  graphql:
    schema:
      locations: classpath*:graphql/**/

server:
  port: 8081

info:
  app:
    name: Landmates Marketplace Service
    description: Marketplace to access products and offered tourism services
    version: 0.0.1

graphql:
  websocket:
    subscriptions:
      enabled: true
  servlet:
    mapping: /graphql
    enabled: true
  playground:
    enabled: true
  graphiql:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
