server:
  port: 8085

eureka:
  instance:
    hostname: reviews-microservice

spring:
  data:
    mongodb:
      uri: mongodb+srv://ms-client:LandMates2024@clusterms.xphsc.mongodb.net/?retryWrites=true&w=majority&appName=ClusterMS
      database: reviews

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
