server-port: 8082
keycloak-url: http://localhost:9090

server:
  port: ${server-port:8082}

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        receiveMessage-in-0:
          destination: user-management
          group: consumer-group
  data:
    mongodb:
      uri: mongodb+srv://ms-client:LandMates2024@clusterms.xphsc.mongodb.net/?retryWrites=true&w=majority&appName=ClusterMS
      database: users

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
