server-port: 8082
kafka-broker: 54.224.168.24:9092

server:
  port: ${server-port:8082}

eureka:
  instance:
    hostname: users-microservice

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${kafka-broker}
      bindings:
        receiveMessage-in-0:
          destination: user-management
          group: consumer-group
  data:
    mongodb:
      uri: mongodb+srv://ms-client:LandMates2024@clusterms.xphsc.mongodb.net/?retryWrites=true&w=majority&appName=ClusterMS
      database: users

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
