version: '3.8'
services:
  cloud-config:
    image: cloud-config:latest 
    container_name: cloud-config
    ports:
      - "8888:8888"
    networks:
      - app-network
  
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network
  
  keycloak-server:
    image: keycloak-server:latest
    container_name: keycloak-server
    ports:
      - "9090:9090"
    networks:
      - app-network

  gateway:
    image: gateway:latest
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - cloud-config
      - eureka-server
      - keycloak-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config:8888
  
  users-microservice:
    image: users-microservice:latest
    container_name: users-microservice
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config:8888
    depends_on:
      - eureka-server
      - keycloak-server
      - cloud-config
  
  marketplace-microservice:
    image: marketplace-microservice:latest
    container_name: marketplace-microservice
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://cloud-config:8888
    depends_on:
      - eureka-server
      - cloud-config

networks:
  app-network:
    driver: bridge
