spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/landmates/protocol/openid-connect/certs

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

keycloak:
  token-url: http://localhost:9090/realms/landmates/protocol/openid-connect/token
  client-id: landmates-gateway
  client-secret: vLGxNN08lTueoHz1hQuhpNm6F2OqaxVB
