spring:
  application:
    name: marketplace
    
  sql:
    init:
      platform: h2

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb+srv://naingmd:nunhx7mYxFLWoGv1@graphql.8rkuykz.mongodb.net/?retryWrites=true&w=majority&appName=GraphQL 

server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: Landmates Marketplace Service
    description: Marketplace to access products and offered tourism services
    version: 0.0.1
  company:
    name: Landmates
    contact:
      email: contact@landmates.co
