### Prueba de registro de usuario

@host = http://localhost:8080

POST {{host}}/keycloak-server/admin/realms/landmates/users
Content-Type: application/json

{
    "credentials": [{
        "temporary": false,
        "type": "password",
        "value": "mypassword2024"
    }],
    "username": "jmudi",
    "firstName": "Juan",
    "lastName": "Munoz",
    "email": "hola@naing.co",
    "emailVerified": false,
    "enabled": true
}