server:
  port: 8888

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config

  profiles:
    active: native
